### ISSUE TITLE
Add favicon, update page title and meta description

### ISSUE THREAD

**Issue by YoussB** [concourse/resource-types-website#169]
AC:
- [x] add the Concourse logo as a favicon.
- [x] should match the favicon on the concourse homepage
- [x] Page title should say 'Concourse Resource Types'
- [x] Meta description: 'A repository for Concourse resource types'

**Comment by ibagha** [comment]
@jomsie Updated the story to change the page title and add a meta description
