### ISSUE TITLE
epic: low hanging fruits

### ISSUE THREAD

**Issue by YoussB** [concourse/resource-types-website#207]
- [x] pipeline merge issue #208 
- [x] stars pipeline and deployment changes #101 
- [x] sanity check job #209
- [x] golang linter problems #213
- [x] ~docker image versioning #212~
